version: "3.8"

services:
  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    restart: unless-stopped

  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    depends_on:
      - guacd
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      GUACAMOLE_HOME: /config
    volumes:
      - ./user-mapping.xml:/config/user-mapping.xml:ro
    restart: unless-stopped
